[[profile]]
name = "dual_home"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    match = "LG Electronics"
    enable = true
    mode = { width = 2560, height = 1440, refresh = 60 }
    #mode = { width = 1920, height = 1080, refresh = 60 }
    position = { x = 0, y = 0 }
    scale = 1

    [[profile.output]]
    match = "Dell Inc."
    enable = true
    exec = ["echo This is output $SHIKANE_OUTPUT_NAME"]
    mode = { width = 1920, height = 1080, refresh = 60 }
    position = { x = 2560, y = 0 }
    #position = { x = 1920, y = 0 }
    scale = 1

    [[profile.output]]
    match = "eDP-1"
    enable = false
    mode = { width = 2880, height = 1800, refresh = 60  }
    position = { x = 0, y = 0 }
    scale = 1.5

[[profile]]
name = "single_home"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    match = "LG Electronics"
    enable = true
    mode = { width = 2560, height = 1440, refresh = 60 }
    #mode = { width = 1920, height = 1080, refresh = 60 }
    position = { x = 1920, y = 0 }
    scale = 1

    [[profile.output]]
    match = "eDP-1"
    enable = false
    mode = { width = 2880, height = 1800, refresh = 60  }
    position = { x = 0, y = 0 }
    scale = 1.5
#exec = [
#    "gsettings set org.gnome.desktop.interface text-scaling-factor 1.0",
#    "gsettings set org.gnome.desktop.interface scaling-factor 1.0",
#    "sed -i 's/font_size 15/font_size 13/' ~/.config/kitty/kitty.conf",
#    "update-kitty.sh"]

[[profile]]
name = "default"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    match = "eDP-1"
    enable = true
    mode = { width = 2880, height = 1800, refresh = 60  }
#    mode = { width = 1920, height = 1200, refresh = 60  }
    position = { x = 0, y = 0 }
    scale = 1
#    exec = ["gsettings set org.gnome.desktop.interface text-scaling-factor 1.4",
#    "sed -i 's/font_size 13/font_size 15/' ~/.config/kitty/kitty.conf",
#    "update-kitty.sh"]
